apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-test
spec:
  selector:
    matchLabels:
      app: k8s-test
  template:
    metadata:
      labels:
        app: k8s-test
    spec:
      containers:
      - name: backend
        image: bstashchuk/k8s-web-hello
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000

          
